### ISSUE TITLE
Spanish translation

### ISSUE THREAD

**Issue by albertmueladote** [fmmmlee/GW2-Addon-Manager#104]
I volunteer for Spanish translations, it seems like a great and incredible idea, I would like everyone to be able to use it without the language being a problem.

**Comment by Draeggiar** [comment]
Translations are located in `application/Localization/StaticText.resx` (each language has its own file). If you want to contrubute, you can create your own file, and then add it to `application/Localization/CultureConstants`. Or you can just translate phrases and ill do the rest.
Here are phrases to translate:

1. Add-Ons
2. Available
3. Chinese
4. Companion Applications
5. Configuration Options
6. Create Shortcut
7. Adds a shortcut to the application to the start menu - if program is moved, the shortcut will not function!
8. Delete
9. Deletes the selected addons and all associated data
10. Disable
11. Disables the selected addons
12. Download complete
13. Downloading
14. English
15. Force Redownload
16. Redownloads the addon loader and all addons regardless of version.
17. French
18. Game path
19. Korean
20. Language
21. Options
22. Programs for GW2 not managed by GW2-UOAOM, such as TacO
23. Re-Enable
24. Enables the selected addons if they are disabled
25. Reset to Clean Install
26. Deletes all addons and plugins from Guild Wars 2.
27. Select all addons that you would like to install or update.
28. Select an add-on to see more information about it.
29. Select Directory
30. Manage the game at the location in the text box
31. Update
32. UPDATE
33. This will download the application update and then restart the program.

**Comment by albertmueladote** [comment]
Done, thanks for your job.
If you need something about this or some translation is not good, plz tell
me.
Have a nice day.

<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
Libre
de virus. www.avast.com
<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
<#DAB4FAD8-2DD7-40BB-A1B8-4E2AA1F9FDF2>

**Comment by Draeggiar** [comment]
I cant see your translations, did you uploaded it?

**Comment by albertmueladote** [comment]
Wow, i did something wrong? Sorry for that, don't understand what happened.
I add the file on this message. (I added spanish to the texts)

**Comment by Draeggiar** [comment]
Im sorry, still cant see the translations. Can you please paste them as plain text, or upload them via github? Maybe there is something wrong if you reply by email.

**Comment by albertmueladote** [comment]
<?xml version="1.0" encoding="utf-8"?>
<root>
  
  <xsd:schema id="root" xmlns="" xmlns:xsd="http://www.w3.org/2001/XMLSchema"
xmlns:msdata="urn:schemas-microsoft-com:xml-msdata">
    <xsd:import namespace="http://www.w3.org/XML/1998/namespace" />
    <xsd:element name="root" msdata:IsDataSet="true">
      <xsd:complexType>
        <xsd:choice maxOccurs="unbounded">
          <xsd:element name="metadata">
            <xsd:complexType>
              <xsd:sequence>
                <xsd:element name="value" type="xsd:string" minOccurs="0" />
              </xsd:sequence>
              <xsd:attribute name="name" use="required" type="xsd:string" />
              <xsd:attribute name="type" type="xsd:string" />
              <xsd:attribute name="mimetype" type="xsd:string" />
              <xsd:attribute ref="xml:space" />
            </xsd:complexType>
          </xsd:element>
          <xsd:element name="assembly">
            <xsd:complexType>
              <xsd:attribute name="alias" type="xsd:string" />
              <xsd:attribute name="name" type="xsd:string" />
            </xsd:complexType>
          </xsd:element>
          <xsd:element name="data">
            <xsd:complexType>
              <xsd:sequence>
                <xsd:element name="value" type="xsd:string" minOccurs="0"
msdata:Ordinal="1" />
                <xsd:element name="comment" type="xsd:string" minOccurs="0"
msdata:Ordinal="2" />
              </xsd:sequence>
              <xsd:attribute name="name" type="xsd:string" use="required"
msdata:Ordinal="1" />
              <xsd:attribute name="type" type="xsd:string"
msdata:Ordinal="3" />
              <xsd:attribute name="mimetype" type="xsd:string"
msdata:Ordinal="4" />
              <xsd:attribute ref="xml:space" />
            </xsd:complexType>
          </xsd:element>
          <xsd:element name="resheader">
            <xsd:complexType>
              <xsd:sequence>
                <xsd:element name="value" type="xsd:string" minOccurs="0"
msdata:Ordinal="1" />
              </xsd:sequence>
              <xsd:attribute name="name" type="xsd:string" use="required" />
            </xsd:complexType>
          </xsd:element>
        </xsd:choice>
      </xsd:complexType>
    </xsd:element>
  </xsd:schema>
  <resheader name="resmimetype">
    <value>text/microsoft-resx</value>
  </resheader>
  <resheader name="version">
    <value>2.0</value>
  </resheader>
  <resheader name="reader">
    <value>System.Resources.ResXResourceReader, System.Windows.Forms,
Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089</value>
  </resheader>
  <resheader name="writer">
    <value>System.Resources.ResXResourceWriter, System.Windows.Forms,
Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089</value>
  </resheader>
  <data name="French" xml:space="preserve">
    <value>FrancÃ©s</value>
  </data>
  <data name="English" xml:space="preserve">
    <value>InglÃ©s</value>
  </data>
  <data name="Chinese" xml:space="preserve">
    <value>Chino</value>
  </data>
  <data name="Korean" xml:space="preserve">
    <value>Coreano</value>
  </data>
  <data name="Spanish" xml:space="preserve">
    <value>EspaÃ±ol</value>
  </data>
  <data name="Language" xml:space="preserve">
    <value>Idioma</value>
  </data>
  <data name="GamePath" xml:space="preserve">
    <value>Ruta del juego</value>
  </data>
  <data name="ProgramsNotManagedByThisApplication" xml:space="preserve">
    <value>Programas para GW2 no gestionados por GW2-UOAOM, como
TacO</value>
  </data>
  <data name="CompanionApplicationsWithLeadingSpace" xml:space="preserve">
    <value> Aplicaciones complementarias</value>
  </data>
  <data name="Options" xml:space="preserve">
    <value>Opciones</value>
  </data>
  <data name="CreateShortcut" xml:space="preserve">
    <value>Crear atajo</value>
  </data>
  <data name="CreateShortcutDescription" xml:space="preserve">
    <value>Agrega un acceso directo a la aplicaciÃ³n en el menÃº de inicio;
si se mueve el programa, Â¡el acceso directo no funcionarÃ¡!</value>
  </data>
  <data name="ForceRedownload" xml:space="preserve">
    <value>Volver a descargar</value>
  </data>
  <data name="ForceRedownloadDescription" xml:space="preserve">
    <value>Vuelve a descargar el cargador de complementos y todos los
complementos, independientemente de la versiÃ³n.</value>
  </data>
  <data name="Available" xml:space="preserve">
    <value>Disponible</value>
  </data>
  <data name="Downloading" xml:space="preserve">
    <value>Descargando</value>
  </data>
  <data name="DownloadComplete" xml:space="preserve">
    <value>Descarga completa</value>
  </data>
  <data name="Update" xml:space="preserve">
    <value>Actualizar</value>
  </data>
  <data name="UpdateDescription" xml:space="preserve">
    <value>Esto descargarÃ¡ la actualizaciÃ³n de la aplicaciÃ³n y luego
reiniciarÃ¡ el programa.</value>
  </data>
  <data name="SelectDirectory" xml:space="preserve">
    <value>Selecciona una carpeta</value>
  </data>
  <data name="SelectDirectoryDescription" xml:space="preserve">
    <value>Selecciona la ubicaciÃ³n del juego</value>
  </data>
  <data name="AddOns" xml:space="preserve">
    <value>Add-Ons</value>
  </data>
  <data name="SelectAllAddonsDescription" xml:space="preserve">
    <value>Seleccione todos los complementos que le gustarÃ­a instalar o
actualizar.</value>
  </data>
  <data name="ConfigurationOptions" xml:space="preserve">
    <value>Opciones de configuraciÃ³n</value>
  </data>
  <data name="Delete" xml:space="preserve">
    <value>Borrar</value>
  </data>
  <data name="Disable" xml:space="preserve">
    <value>Desactivar</value>
  </data>
  <data name="DeleteDescription" xml:space="preserve">
    <value>Elimina los complementos seleccionados y todos los datos
asociados</value>
  </data>
  <data name="DisableDescription" xml:space="preserve">
    <value>Deshabilita los complementos seleccionados</value>
  </data>
  <data name="ReEnable" xml:space="preserve">
    <value>Reactivar</value>
  </data>
  <data name="ReEnableDescription" xml:space="preserve">
    <value>Habilita los complementos seleccionados si estÃ¡n
deshabilitados</value>
  </data>
  <data name="ResetToCleanInstall" xml:space="preserve">
    <value>Restablecer la configuraciÃ³n inicial</value>
  </data>
  <data name="ResetToCleanInstallDescription" xml:space="preserve">
    <value>Elimina todos los complementos y complementos de Guild Wars
2.</value>
  </data>
  <data name="UpdateAllUpperCase" xml:space="preserve">
    <value>ACTUALIZAR</value>
  </data>
  <data name="SelectAnAddonToSeeMoreInformationAboutIt"
xml:space="preserve">
    <value>Seleccione un complemento para ver mÃ¡s informaciÃ³n sobre
Ã©l.</value>
  </data>
</root>
